#!/bin/bash
BASEDIR=$(dirname "$0")
export BELA_IP=${BELA_IP:=192.168.7.2}
export BELA_ROOT=${BELA_ROOT:="`realpath $BASEDIR/..`"}
export BBB_ADDRESS=root@$BELA_IP

PLATFORM=`uname`
if [ "${PLATFORM}" = "Darwin" ]; then
    export TOOLCHAIN=/usr/local/opt
    export CLANG=$TOOLCHAIN/llvm/bin/clang++
else
    export TOOLCHAIN=/usr/lib/llvm-10
    export CLANG=/usr/bin/clang++-10
fi 

# echo export TOOLCHAIN=$TOOLCHAIN
# echo export CLANG=$CLANG

#bela config for details
#/root/Bela/resources/bin/bela-config --defines
#-DXENOMAI_SKIN_posix
#/root/Bela/resources/bin/bela-config --includes
#/root/Bela/include
#/root/Bela/resources/bin/bela-config --libraries
#-L/usr/xenomai/lib -L/root/Bela/lib -lbela -lcobalt -lmodechk -lpthread -lrt
#/root/Bela/resources/bin/bela-config --cflags
#-march=armv7-a -mtune=cortex-a8 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math
#/root/Bela/resources/bin/bela-config --cxxflags
#-march=armv7-a -mtune=cortex-a8 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math

export BELA_C_OPTS="-DXENOMAI_SKIN_posix -march=armv7-a -mtune=cortex-a8 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math"
export BELA_C_OPTS="-O3 -fPIC ${BELA_C_OPTS} "

# -I$BELA_ROOT/sysroot/usr/local/include \

export BELA_OPTIONS=" \
    -I$BELA_ROOT/sysroot/root/Bela/include \
    -I$BELA_ROOT/sysroot/usr/xenomai/include \
    -L$BELA_ROOT/sysroot/root/Bela/lib \
    -L$BELA_ROOT/sysroot/usr/local/lib \
    -Wl,--no-as-needed -L$BELA_ROOT/sysroot/usr/xenomai/lib \
    -lcobalt -lmodechk -lpthread -lrt\
    -lprussdrv -lstdc++ -lasound -lseasocks -lNE10 -lmathneon -ldl \
    -lbela -lbelaextra \
"


export X_OPTS=" \
 --target=arm-linux-gnueabihf \
 --sysroot=$BELA_ROOT/sysroot \
 -isysroot $BELA_ROOT/sysroot \
 -isystem $BELA_ROOT/sysroot/usr/include/c++/6.3.0 \
 -isystem $BELA_ROOT/sysroot/usr/include/arm-linux-gnueabihf/c++/6.3.0 \
 -L$BELA_ROOT/sysroot/usr/lib/gcc/arm-linux-gnueabihf/6.3.0 \
 -B$BELA_ROOT/sysroot/usr/lib/gcc/arm-linux-gnueabihf/6.3.0 \
 --gcc-toolchain=TOOLCHAIN/arm-linux-gnueabihf-binutils \
"

FILE=$1
MAIN=`realpath $BELA_ROOT/sysroot/root/Bela/default_main.cpp`
OUTFILE="${FILE%.*}"


echo ${CLANG} ${X_OPTS} ${BELA_C_OPTS} ${BELA_OPTIONS} -o ${OUTFILE} ${FILE} ${MAIN}
${CLANG} ${X_OPTS} ${BELA_C_OPTS} ${BELA_OPTIONS} -o ${OUTFILE} ${FILE} ${MAIN}
