#!/bin/bash
BASEDIR=$(dirname "$0")
export XC_IP=${XC_IP:=192.168.7.2}
export XC_ROOT=${XC_ROOT:="`realpath $BASEDIR/..`"}

XC_SYSROOT=${XC_ROOT}/sysroot


PLATFORM=`uname`
if [ "${PLATFORM}" = "Darwin" ]; then
    export TOOLCHAIN=/usr/local/opt
    export CLANG=$TOOLCHAIN/llvm/bin/clang++
else
    export TOOLCHAIN=/usr/lib/llvm-10
    export CLANG=/usr/bin/clang++-10
fi 

# echo export TOOLCHAIN=$TOOLCHAIN
# echo export CLANG=$CLANG

#bela config for details
#/root/Bela/resources/bin/bela-config --defines
#-DXENOMAI_SKIN_posix
#/root/Bela/resources/bin/bela-config --includes
#/root/Bela/include
#/root/Bela/resources/bin/bela-config --libraries
#-L/usr/xenomai/lib -L/root/Bela/lib -lbela -lcobalt -lmodechk -lpthread -lrt
#/root/Bela/resources/bin/bela-config --cflags
#-march=armv7-a -mtune=cortex-a8 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math
#/root/Bela/resources/bin/bela-config --cxxflags
#-march=armv7-a -mtune=cortex-a8 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math

export BELA_C_OPTS="-DXENOMAI_SKIN_posix -march=armv7-a -mtune=cortex-a8 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math"
export BELA_C_OPTS="-O3 -fPIC ${BELA_C_OPTS} "
export BELA_C_OPTS=" \
    -I${XC_SYSROOT}/root/Bela \
    -I${XC_SYSROOT}/root/Bela/include \
    -I${XC_SYSROOT}/usr/xenomai/include \
"


# -I$XC_SYSROOT/usr/local/include \

export BELA_LD_OPTS=" \
    -Wl,--no-as-needed \
    -L${XC_SYSROOT}/usr/local/lib \
    -L${XC_SYSROOT}/usr/xenomai/lib \
    -L${XC_SYSROOT}/root/Bela/lib \
    -lcobalt -lmodechk -lpthread -lrt\
    -lprussdrv -lstdc++ -lasound -lseasocks -lNE10 -lmathneon -ldl \
    -latomic \
    -l:libbelafull.a\
"


export XC_OPTS=" \
 --target=arm-linux-gnueabihf \
 --sysroot=${XC_SYSROOT} \
 -isysroot ${XC_SYSROOT} \
 -isystem ${XC_SYSROOT}/usr/include/c++/6.3.0 \
 -isystem ${XC_SYSROOT}/usr/include/arm-linux-gnueabihf/c++/6.3.0 \
 -L${XC_SYSROOT}/usr/lib/gcc/arm-linux-gnueabihf/6.3.0 \
 -B${XC_SYSROOT}/usr/lib/gcc/arm-linux-gnueabihf/6.3.0 \
 --gcc-toolchain=TOOLCHAIN/arm-linux-gnueabihf-binutils \
"
export XC_CPPFLAGS="${BELA_C_OPTS} ${CPPFLAGS}"
export XC_LDFLAGS="${BELA_LD_OPTS} ${LDFLAGS}"

MAIN=`realpath $XC_ROOT/Bela/Core/default_main.cpp`

OUTFILE=$1

set -x
${CLANG} ${XC_OPTS} ${XC_CPPFLAGS} ${MAIN} *.cpp ${XC_LDFLAGS} -o ${OUTFILE} 
set +x
