#!/bin/bash
BASEDIR=$(dirname "$0")
export XC_IP=${XC_IP:=192.168.7.2}
export XC_ROOT=${XC_ROOT:="`realpath $BASEDIR/..`"}
export XC_CL_OPTS=${XC_CL_OPTS:=" "}

## ide defaults are: -p 16 -C 8 -B 16 -H -6 -N 1 -G 1 -M 0 -D 0 -A --pga-gain-left 10 --pga-gain-right 10
## however, these are in the -h text anyway, so easier to read there ;) 


xcExec() {
    ssh -o LogLevel=ERROR $BBB_ADDRESS "$*"
}

xcCopy() {
    scp -o LogLevel=ERROR $1 $BBB_ADDRESS:$2
}

xcExec mkdir -p ./tmp
xcCopy $1 ./tmp/$1
xcExec "(cd ./tmp;./$* ${XC_CL_OPTS} )"
xcExec "killall $1"
