#!/bin/bash
BASEDIR=$(dirname "$0")
export XC_IP=${XC_IP:=192.168.7.2}
export XC_ROOT=${XC_ROOT:="`realpath $BASEDIR/..`"}
export XC_CL_OPTS=${XC_CL_OPTS:=" "}
export XC_SSH=${XC_SSH:=root@$XC_IP}

ping -c 1 -t 1 $XC_IP >/dev/null 2>&1 
if [ $? -ne 0 ]; then
    echo WARNING: unable to connect to ${XC_IP}, check XC_IP?
    exit -1
fi


xcExec() {
    ssh -o LogLevel=ERROR $XC_SSH "$*"
}

xcCopy() {
    scp -o LogLevel=ERROR $1 $XC_SSH:$2
}

xcExec mkdir -p ./tmp
xcCopy $1 ./tmp/$1
xcExec "(cd ./tmp;./$* ${XC_CL_OPTS} )"
xcExec "killall $1"
